#!/bin/bash

e=0

if ! which zenity > /dev/null 2>&1
then
    e=1
fi

if ! which wmctrl > /dev/null 2>&1
then
    if [ "$e" -eq 1 ]
    then 
        e=3
    else   
        e=2
    fi
fi

case $e in
    1)
        echo "You need to install zenity, before setting up an alarm"
        exit 1
        ;;
    2)
        echo "You need to install wmctrl, before setting up an alarm"
        exit 1
        ;;
    3)
        echo "You need to install both zenity and wmctrl, before setting up an alarm"
        exit 1
        ;;
esac

if [ "$1" = "" ]
then 
    echo "Time is to be specified"
    exit 1
fi

case $2 in
    sec)
        time=$(($1))
        ;;
    min)
        time=$(($1*60))
        ;;
    hr)
        time=$(($1*60*60))
        ;;
    *)
        echo "Time unit is to be specified"
        exit 1
        ;;
esac

a=$(date | cut -d " " -f5)

if [ "$3" != "" ]
then
    msg=$3
else
    msg="Time to switch :)"
fi

(sleep $(($time + 1)) && wmctrl -F -a "Alarm" -b add,above) &
(sleep $time && zenity --info --title="Alarm" --text="<span font='25' color='blue'><b>\n\n\t$a\n$msg</b></span>" --icon-name="" > /dev/null 2>&1) &