#!/bin/bash
#
#
if which youtube-dl
then
echo "Downloader Exists!"
else
apt-get update
apt-get install youtube-dl
fi
#
#
link=$(strings ~/.config/google-chrome/Default/Current\ Session | grep youtube.*watch?v | uniq -d | tail -1)
#
#
echo "Downloading: $link"
#
#
youtube-dl $link

